(define (problem problema) 
(:domain dominio) 
(:objects Sala1 Sala2 Sala3 Sala4 Corredor1 Deposito1)
(:init (Em Deposito1) (Sala Sala1) (Sala Sala2) (Sala Sala3) (Sala Sala4) (Corredor Corredor1) (Deposito Deposito1))
(:goal (Em Sala1)) 
)
